apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: us-east1-docker.pkg.dev/iti-gcp-course/iti/project:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: python-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer